/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UdemyDealsRouteImport } from './routes/udemy-deals'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AdvertiserDisclosureRouteImport } from './routes/advertiser-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const UdemyDealsRoute = UdemyDealsRouteImport.update({
  id: '/udemy-deals',
  path: '/udemy-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiserDisclosureRoute = AdvertiserDisclosureRouteImport.update({
  id: '/advertiser-disclosure',
  path: '/advertiser-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertiser-disclosure': typeof AdvertiserDisclosureRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/courses': typeof CoursesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/udemy-deals': typeof UdemyDealsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertiser-disclosure': typeof AdvertiserDisclosureRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/courses': typeof CoursesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/udemy-deals': typeof UdemyDealsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertiser-disclosure': typeof AdvertiserDisclosureRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/courses': typeof CoursesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/udemy-deals': typeof UdemyDealsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertiser-disclosure'
    | '/affiliate-disclosure'
    | '/blog'
    | '/contact'
    | '/cookie'
    | '/courses'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/udemy-deals'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertiser-disclosure'
    | '/affiliate-disclosure'
    | '/contact'
    | '/cookie'
    | '/courses'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/udemy-deals'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertiser-disclosure'
    | '/affiliate-disclosure'
    | '/blog'
    | '/contact'
    | '/cookie'
    | '/courses'
    | '/disclaimer'
    | '/privacy'
    | '/terms'
    | '/udemy-deals'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertiserDisclosureRoute: typeof AdvertiserDisclosureRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookieRoute: typeof CookieRoute
  CoursesRoute: typeof CoursesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UdemyDealsRoute: typeof UdemyDealsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/udemy-deals': {
      id: '/udemy-deals'
      path: '/udemy-deals'
      fullPath: '/udemy-deals'
      preLoaderRoute: typeof UdemyDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertiser-disclosure': {
      id: '/advertiser-disclosure'
      path: '/advertiser-disclosure'
      fullPath: '/advertiser-disclosure'
      preLoaderRoute: typeof AdvertiserDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertiserDisclosureRoute: AdvertiserDisclosureRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CookieRoute: CookieRoute,
  CoursesRoute: CoursesRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UdemyDealsRoute: UdemyDealsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
